// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: feeds.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (id, url, user_id) VALUES ($1, $2, $3) RETURNING id, url, user_id
`

type CreateFeedParams struct {
	ID     uuid.UUID
	Url    string
	UserID uuid.UUID
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.ID, arg.Url, arg.UserID)
	var i Feed
	err := row.Scan(&i.ID, &i.Url, &i.UserID)
	return i, err
}
